/* * ======================================================================================
 * SCRIPT: 04_logistics_setup.sql
 * AUTHOR: KCB Kris
 * PL: Konfiguracja środowiska GreenStream Logistics (Symulacja problemów wydajnościowych)
 * EN: GreenStream Logistics environment setup (Performance issues simulation)
 * ORACLE VERSION: 23ai
 * ======================================================================================
 */

SET SERVEROUTPUT ON
SET TIMING ON

-- 1. CLEANUP (Safe environment reset)
-- PL: Usunięcie starych tabel, jeśli istnieją
-- EN: Dropping old tables if they exist
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('LOGISTICS_EVENTS', 'ORDERS', 'CUSTOMERS', 'PERF_KNOWLEDGE_BASE')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' PURGE';
        DBMS_OUTPUT.PUT_LINE('[INFO] Dropped table: ' || t.table_name);
    END LOOP;
END;
/

-- 2. CREATE TABLES (Intentionally unoptimized)

-- PL: Tabela Klienci - brak indeksu na kolumnie email (częsty błąd)
-- EN: Customers table - missing index on email column (common mistake)
CREATE TABLE customers (
    cust_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR2(100),
    full_name       VARCHAR2(100),
    region          VARCHAR2(50),
    created_at      DATE DEFAULT SYSDATE
);

-- PL: Tabela Zamówienia - celowy brak klucza obcego (FK) do customers
-- EN: Orders table - intentional lack of Foreign Key (FK) to customers
CREATE TABLE orders (
    order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_id         NUMBER, 
    order_date      DATE,
    status          VARCHAR2(20), -- 'NEW', 'SHIPPED', 'DELIVERED', 'RETURNED'
    total_amount    NUMBER(10, 2),
    notes           VARCHAR2(4000) -- PL: Dane nieustrukturyzowane / EN: Unstructured data
);

-- PL: Tabela Zdarzenia Logistyczne - duży wolumen danych
-- EN: Logistics Events table - high data volume
CREATE TABLE logistics_events (
    event_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER,
    event_type      VARCHAR2(50), -- 'SCAN_WAREHOUSE', 'IN_TRANSIT', 'LAST_MILE'
    event_loc       VARCHAR2(100),
    event_ts        TIMESTAMP,
    scanner_id      VARCHAR2(20)
);

-- PL: Baza Wiedzy RAG - Tabela z wektorami rozwiązań
-- EN: RAG Knowledge Base - Table with solution vectors
CREATE TABLE perf_knowledge_base (
    kb_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_category  VARCHAR2(50),   -- e.g., 'MISSING_INDEX', 'LOCK_CONTENTION'
    sql_signature   VARCHAR2(100),  -- SQL_ID or Hash
    problem_desc    VARCHAR2(4000), -- PL: Opis problemu dla człowieka / EN: Human readable description
    solution_script CLOB,           -- PL: Gotowy skrypt naprawczy / EN: Ready-to-use fix script
    -- PL: Wektor 384-wymiarowy (model all-MiniLM-L12-v2)
    -- EN: 384-dimensional vector (all-MiniLM-L12-v2 model)
    embedding       VECTOR(384, FLOAT32)
);

-- 3. DATA GENERATION (Bulk Simulation)
DECLARE
    v_statuses sys.odcivarchar2list := sys.odcivarchar2list('NEW', 'SHIPPED', 'DELIVERED', 'RETURNED');
    v_regions  sys.odcivarchar2list := sys.odcivarchar2list('EMEA', 'NA', 'APAC', 'LATAM');
    v_cust_id  NUMBER;
    v_order_id NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('[INFO] Generating Customers (approx 5k)...');
    
    -- PL: Generowanie 5000 klientów
    -- EN: Generating 5000 customers
    FOR i IN 1..5000 LOOP
        INSERT INTO customers (email, full_name, region, created_at)
        VALUES (
            'user_' || i || '@greenstream.com',
            'Customer ' || i,
            v_regions(TRUNC(DBMS_RANDOM.VALUE(1, 5))),
            SYSDATE - DBMS_RANDOM.VALUE(1, 365)
        ) RETURNING cust_id INTO v_cust_id;
        
        -- PL: Generowanie 1-3 zamówień dla każdego klienta
        -- EN: Generating 1-3 orders for each customer
        FOR j IN 1..TRUNC(DBMS_RANDOM.VALUE(1, 4)) LOOP
            INSERT INTO orders (cust_id, order_date, status, total_amount, notes)
            VALUES (
                v_cust_id,
                SYSDATE - DBMS_RANDOM.VALUE(1, 60),
                v_statuses(TRUNC(DBMS_RANDOM.VALUE(1, 5))),
                ROUND(DBMS_RANDOM.VALUE(50, 5000), 2),
                'Order notes check ' || DBMS_RANDOM.STRING('X', 10)
            ) RETURNING order_id INTO v_order_id;

            -- PL: Generowanie 2-5 zdarzeń logistycznych na zamówienie
            -- EN: Generating 2-5 logistic events per order
            FOR k IN 1..TRUNC(DBMS_RANDOM.VALUE(2, 6)) LOOP
                INSERT INTO logistics_events (order_id, event_type, event_loc, event_ts, scanner_id)
                VALUES (
                    v_order_id,
                    'SCAN_' || DBMS_RANDOM.STRING('U', 5),
                    'WAREHOUSE_' || TRUNC(DBMS_RANDOM.VALUE(1, 10)),
                    SYSDATE - DBMS_RANDOM.VALUE(0, 10),
                    'SCN-' || TRUNC(DBMS_RANDOM.VALUE(100, 999))
                );
            END LOOP;
        END LOOP;
        
        -- Commit every 500 rows to manage undo logs
        IF MOD(i, 500) = 0 THEN COMMIT; END IF;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('[SUCCESS] Data generation complete.');
END;
/
